[package]
name = "Realm_V1"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.28"
egui = "0.28"
webbrowser = "1.0"
rfd = "0.14"
env_logger = "0.11"
serde = { version = "1.0", features = ["derive"] }